# Writes OUT with the commit this build came from, for the first line of console.log.
# A git checkout gives `git describe`; a GitHub source download has no .git, so the commit comes from
# git_archive_version.txt, which `git archive` fills in (export-subst in .gitattributes).
set(version "")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${REPO}" describe --always --dirty --abbrev=7
                    OUTPUT_VARIABLE version OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0)
        set(version "")
    endif()
endif()
if(version STREQUAL "" AND EXISTS "${REPO}/runtime/cmake/git_archive_version.txt")
    file(READ "${REPO}/runtime/cmake/git_archive_version.txt" archived)
    string(STRIP "${archived}" archived)
    if(NOT archived MATCHES "Format")
        set(version "${archived} (source download)")
    endif()
endif()
if(version STREQUAL "")
    set(version "unknown")
endif()
set(content "#pragma once\n#define MSC_BUILD_VERSION \"${version}\"\n")
if(EXISTS "${OUT}")
    file(READ "${OUT}" previous)
endif()
if(NOT "${previous}" STREQUAL "${content}")
    file(WRITE "${OUT}" "${content}")
endif()
