#!/usr/bin/env python3
"""Writes Kamek's externals file for Mario Strikers Charged (R4QE01) from the decomp's symbol map.

A code mod calls the game's functions and reads its globals by name; Kamek resolves those names
with this file (`name=0xADDRESS`, one per line). The names are CodeWarrior's mangled ones, as the
decomp's config/R4QE01/symbols.txt has them, so a mod built against the decomp's headers links
straight to the game's own code.

    gen-externals.py <decomp>/config/R4QE01/symbols.txt sdk/kamek/externals-R4QE01.txt
"""

import re
import sys

LINE = re.compile(r'^\s*("(?:[^"\\]|\\.)*"|\S+)\s*=\s*\.(\w+):0x([0-9A-Fa-f]{8});(.*)$')


def main(source: str, target: str) -> None:
    chosen = {}  # name -> (address, rank): a global or weak symbol wins over a local one
    for line in open(source, encoding="utf-8"):
        match = LINE.match(line)
        if not match:
            continue
        name, section, address, rest = match.groups()
        if name.startswith('"'):
            name = name[1:-1]
        if "=" in name or name.startswith("..."):
            continue  # not something a mod can name
        rank = 1 if "scope:local" in rest else 0
        if name not in chosen or rank < chosen[name][1]:
            chosen[name] = (int(address, 16), rank)
    with open(target, "w", encoding="utf-8", newline="\n") as out:
        out.write("# Mario Strikers Charged (R4QE01): the game's symbols for Kamek code mods.\n")
        out.write("# Generated by sdk/kamek/gen-externals.py from the decomp's config/R4QE01/symbols.txt.\n")
        for name, (address, _) in sorted(chosen.items(), key=lambda item: (item[1][0], item[0])):
            out.write(f"{name}=0x{address:08X}\n")
    print(f"{len(chosen)} symbols -> {target}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
